services:

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  monsters-database:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: monsters

  heroes-database:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: heroes

  dungeons-database:
    image: mariadb
    restart: always
    ports:
      - 3308:3306
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: dungeons
