services:

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  monsters-database:
    image: mariadb
    container_name: monsters-database
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: monsters

  heroes-database:
    image: mariadb
    container_name: heroes-database
    restart: always
    ports:
      - 3307:3306
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: heroes

  dungeons-database:
    image: mariadb
    container_name: dungeons-database
    restart: always
    ports:
      - 3308:3306
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: dungeons

  elasticsearch:
    image: elasticsearch:8.17.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:8.17.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200