openapi: '3.0.3'
info:
  title: Dungeons API
  version: '1.0.0'
servers:
  - url: http://localhost:8082/api
tags:
  - name: heroes
paths:
  /dungeons:
    get:
      tags:
        - heroes
      summary: Get all dungeons
      description: 'Gets all dungeons.'
      responses:
        '200':
          description: OK
          content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Dungeon'
  /dungeons/{id}:
    get:
      tags:
        - heroes
      summary: Get a dungeon
      description: 'Gets dungeon by its id.'
      parameters:
        - name: id
          in: path
          description: ID of the dungeon
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Dungeon'
        '404':
          description: Not found
  /dungeons/{dungeonId}/rooms/{roomId}:
    get:
      tags:
        - heroes
      summary: Get a room
      description: 'Gets a room by its id in a dungeon by its id, the heroId query param is used to instantiate the monster of the room.'
      parameters:
        - name: dungeonId
          in: path
          description: ID of the dungeon
          required: true
          schema:
            type: integer
        - name: roomId
          in: path
          description: ID of the room
          required: true
          schema:
            type: integer
        - name: heroId
          in: query
          description: ID of the hero
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        '404':
          description: Not found
components:
  schemas:
    Dungeon:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'Donjon 1'
        rooms:
          type: array
          items:
              $ref: '#/components/schemas/Room'
    Room:
      type: object
      properties:
        id:
          type: integer
          example: '1'
        name:
          type: string
          example: 'Salle 1'
        monsterId:
          type: integer
          example: '3'